name: .NET

on: [ push, pull_request ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build
    - name: List files in the repository
      run: ls ${{ github.workspace }}
    - name: Dotnet Tools
      run: |
        echo "Workspace path ${{ github.workspace }}."
        echo "the preinstalled tools are located here on the runner ${{ runner.tool_cache }}."
        ls ${{ runner.tool_cache }}
    - name: Generate Swagger File
      run: dotnet msbuild -target:GenerateSwaggerFile ${{ github.workspace }}/project.webapi      
