name: .NET

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish --no-build -c Release -o ${{evn.DOTNET_ROOT}}/app
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{evn.DOTNET_ROOT}}/app
  generate-swagger:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      - name: List files in the repository
        run: ls ${{ github.workspace }}
    # - name: Generate Swagger File
    #   run: dotnet msbuild -target:GenerateSwaggerFile ${{ github.workspace }}/project.webapi      
