name: .NET

#on: [ push, pull_request ]
on: 
  workflow_dispatch:
    inputs:
      api_version:
        description: 'Enter the API version number (e.g. 1.2.3)'
        required: true
        default: '1.0.0'
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Generate Swagger File
      run: dotnet msbuild -target:GenerateSwaggerFile ${{ github.workspace }}/project.webapi --nologo -p:api_version=${{github.event.input.api_version}} -p:api_document_version=v1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: swagger-artifact
        path: swagger.json
